# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Core
gem 'roda', '~> 3.16'
gem 'qudo', path: '../..'

# API
gem 'graphql', '~> 1.9'

